frontier/Frontier/urls.py
from django.contrib import admin
from django.urls import path, include
from titans.views import IndexView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('titans/', include('titans.urls')),
    path('pilots/', include('pilots.urls')),
    path('weapons/', include('weapons.urls')),
    path('users/', include('users.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path("__debug__/", include("debug_toolbar.urls")),
])

# if settings.DEBUG:
#     urlpatterns.append(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

admin.site.site_header = 'Управление сайтом TitanFun2'
admin.site.index_title = 'Администрирование Базы Данных'

frontier/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import *

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', CreateUserView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUserView.as_view(), name='profile'),
    path('password-change/', NewPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', NewPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset/', NewPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', NewPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>', NewPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', NewPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),

]

frontier/users/models.py
from django.core.mail import send_mail
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.timezone import now


class Profile(models.Model):
    class Meta:
        verbose_name = 'Профили'
        verbose_name_plural = 'Профиль'

    user = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE,
                                verbose_name='Связанный пользователь')
    bio = models.TextField(max_length=500, blank=True, null=True, verbose_name='О себе')
    photo = models.ImageField(upload_to='user_images/%Y/%m/%d', blank=True, null=True,
                              verbose_name='Фотография пользователя')
    is_email_verified = models.BooleanField(default=False)

    def __str__(self):
        return f'Профиль пользователя: {self.user.username}'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class EmailVerificationModel(models.Model):
    class Meta:
        verbose_name = 'Записи подтверждения E-mail'
        verbose_name_plural = 'Запись подтверждения E-mail'

    code = models.UUIDField(unique=True, verbose_name='Уникальный код')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='Время создания запроса')
    expiration_time = models.DateTimeField(verbose_name='Время истечения запроса')

    def __str__(self):
        return f'Подтверждение почты для пользователя: {self.user.username}'

    def send_verification_email(self):
        address = reverse('users:email_verification', kwargs={'code': self.code, 'email': self.user.email})
        full_address = settings.DOMAIN_NAME + address
        subject = f'Подтверждение E-mail для пользователя {self.user.username}'
        message = f'Для того, чтобы подтвердить свой адрес электронной почты, перейдите по ссылке: {full_address}'
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email]
        )

    def is_expired(self):
        return True if now() >= self.expiration_time else False

frontier/users/forms.py
import django.forms as forms
from django.forms import FileInput

from users.tasks import send_verification_email, send_reset_mail_task
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth.forms import PasswordResetForm as PasswordResetFormCore
from users.models import Profile


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'type': 'username',
            'placeholder': 'Имя пользователя'
        }
    ))
    password = forms.CharField(max_length=16, widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Пароль'
        }
    ))


class CreateUserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'type': 'username',
            'placeholder': 'Имя пользователя'
        }
    ))
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'type': 'first_name',
            'placeholder': 'Имя'
        }
    ))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'type': 'last_name',
            'placeholder': 'Фамилия'
        }
    ))
    email = forms.EmailField(widget=forms.TextInput(
        attrs={
            'type': 'email',
            'placeholder': 'E-mail'
        }
    ))
    password1 = forms.CharField(max_length=16, widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Пароль'
        }
    ))
    password2 = forms.CharField(max_length=16, widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Повтор пароля'
        }
    ))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой E-mail уже существует')
        return email

    def save(self, commit=True):
        user = super().save(commit=True)
        send_verification_email.delay(user.id)
        return user


class UserProfileMainForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Имя пользователя')
    email = forms.EmailField(disabled=True, label='E-mail')

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'Введите Имя'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Введите Фамилию'}),
        }


class UserProfileSubForm(forms.ModelForm):
    photo = forms.ImageField(label='Выберите изображение', widget=forms.FileInput(attrs={'style': 'display: none'}))

    class Meta:
        model = Profile
        fields = ['photo']


class NewPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Введите старый пароль'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Введите новый пароль'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Повторите пароль'}))


class PasswordResetForm(PasswordResetFormCore):
    email = forms.EmailField(max_length=254, widget=forms.TextInput(attrs={'placeholder': 'Email'}))

    def send_reset_mail(self, subject_template_name, email_template_name, context,
                        from_email, to_email, html_email_template_name=None):
        context['user'] = context['user'].id

        send_reset_mail_task.delay(subject_template_name=subject_template_name,
                                   email_template_name=email_template_name,
                                   context=context, from_email=from_email, to_email=to_email,
                                   html_email_template_name=html_email_template_name)


class NewSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Введите новый пароль'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Повторите пароль'}))

frontier/users/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, TemplateView

from users.forms import *
from users.models import EmailVerificationModel


class UserLoginView(LoginView):
    form_class = UserLoginForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}

    def get_success_url(self):
        return reverse_lazy('index')


class CreateUserView(CreateView):
    form_class = CreateUserForm
    template_name = 'users/registration.html'
    extra_context = {'title': 'Регистрация'}

    def get_success_url(self):
        return reverse_lazy('users:login')


class ProfileUserView(LoginRequiredMixin, View):
    def get(self, request):
        main_form = UserProfileMainForm(instance=request.user)
        sub_form = UserProfileSubForm(instance=request.user.profile)

        context = {
            'title': 'Профиль',
            'main_form': main_form,
            'sub_form': sub_form,
        }

        return render(request, 'users/profile.html', context=context)

    def post(self, request):
        main_form = UserProfileMainForm(request.POST, instance=request.user)
        sub_form = UserProfileSubForm(request.POST, request.FILES, instance=request.user.profile)
        if main_form.is_valid() and sub_form.is_valid():
            main_form.save()
            sub_form.save()

            context = {
                'title': 'Профиль',
                'main_form': main_form,
                'sub_form': sub_form,
            }

            return render(request, 'users/profile.html', context=context)

        else:
            messages.error(request, 'Пожалуйста, исправьте ошибки.')


class NewPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    form_class = NewPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change.html'
    extra_context = {'title': 'Изменение пароля'}


class NewPasswordChangeDoneView(LoginRequiredMixin, PasswordChangeDoneView):
    template_name = 'users/password_change_done.html'


class NewPasswordResetView(PasswordResetView):
    form_class = PasswordResetForm
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')


class NewPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'


class NewPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = NewSetPasswordForm
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


class NewPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'


class EmailVerificationView(TemplateView):
    extra_context = {'title': 'E-mail подтвержден'}
    template_name = 'users/verified_email.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = get_user_model().objects.get(email=kwargs['email'])
        email_verifications = EmailVerificationModel.objects.filter(user=user, code=code)
        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.profile.is_email_verified = True
            user.save()
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('index'))

frontier/users/templates/users/image_input.html
<input type="file">

frontier/users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/users/basic.css' %}">
    <link rel="stylesheet" href="{% static 'css/users/login.css' %}">
{% endblock %}

{% block content %}
    <div class="wrapper">
        <h1>Авторизация</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>

            <div class="input-box">{{ form.username }}<i class="fa-solid fa-user"></i></div>
            <div class="form-error">{{ form.username.errors }}</div>

            <div class="input-box">{{ form.password }}<i class="fa-solid fa-lock"></i></div>
            <div class="form-error">{{ form.password.errors }}</div>

            <div class="remember-forgot">
                <label><input type="checkbox"> Запомнить меня</label>
                <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
            </div>
            <button type="submit" class="btn1">Войти</button>
            <div class="register-link">Еще нет аккаунта? <a href="{% url 'users:register' %}">Зарегистрироваться</a>
            </div>
            <div class="col item-social">
                <a class="" href="{% url "social:begin" "github" %}">
                    <i class="fa-brands fa-github"></i></a>
                <a class="unactive" href="#">
                    <i class="fa-brands fa-instagram"></i></a>
                <a class="unactive" href="#">
                    <i class="fa-brands fa-facebook"></i></a>
                <a class="" href="{% url "social:begin" "google-oauth2" %}">
                    <i class="fa-brands fa-google"></i></a>
            </div>
        </form>
    </div>
{% endblock %}

frontier/users/templates/users/password_change.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" href="{% static 'css/users/basic.css' %}">
	<link rel="stylesheet" href="{% static 'css/users/password_change.css' %}">
{% endblock %}

{% block content %}
	<div class="wrapper">
        <h1>Смена пароля</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>

            <div class="input-box">{{ form.old_password }}<i class="fa-solid fa-lock"></i></div>
            <div class="form-error">{{ form.old_password.errors }}</div>

            <div class="input-box">{{ form.new_password1 }}<i class="fa-solid fa-lock"></i></div>
            <div class="form-error">{{ form.new_password1.errors }}</div>

            <div class="input-box">{{ form.new_password2 }}<i class="fa-solid fa-lock"></i></div>
            <div class="form-error">{{ form.new_password2.errors }}</div>

            <button type="submit" class="btn1">Изменить пароль</button>
        </form>
    </div>
{% endblock %}

frontier/users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/users/basic.css' %}">
    <link rel="stylesheet" href="{% static 'css/users/password_change_done.css' %}">
{% endblock %}

{% block content %}
    <div class="wrapper">
        <h1>Изменение пароля прошло успешно!</h1>
        <div class="buttn1">
            <a class="link1" href="{% url 'users:profile' %}">Вернуться к редактированию профиля</a>
        </div>
    </div>
{% endblock %}

frontier/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/users/basic.css' %}">
    <link rel="stylesheet" href="{% static 'css/users/password_reset_complete.css' %}">
{% endblock %}

{% block content %}
    <div class="wrapper">
        <h1>Пароль восстановлен</h1>
        <form method="get" action="{% url 'users:login' %}">
            <button class="btn1" type="submit">Вернуться к авторизации</button>
        </form>
    </div>
{% endblock %}

frontier/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/users/basic.css' %}">
    <link rel="stylesheet" href="{% static 'css/users/password_reset_confirm.css' %}">
{% endblock %}

{% block content %}
    <div class="wrapper">
        <h1>Восстановление пароля</h1>
        {% if validlink %}

            <p>{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

            <form action="" method="post">
                {% csrf_token %}
                <div class="form-error">{{ form.non_field_errors }}</div>

                <div class="input-box">{{ form.new_password1 }}<i class="fa-solid fa-lock"></i></div>
                <div class="form-error">{{ form.new_password1.errors }}</div>

                <div class="input-box">{{ form.new_password2 }}<i class="fa-solid fa-lock"></i></div>
                <div class="form-error">{{ form.new_password2.errors }}</div>


                <button type="submit" class="btn1">Сменить пароль</button>
            </form>

        {% else %}

            <p>{% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

        {% endif %}
    </div>
{% endblock %}

frontier/users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/users/basic.css' %}">
    <link rel="stylesheet" href="{% static 'css/users/password_reset_done.css' %}">
{% endblock %}

{% block content %}
    <div class="wrapper">
        <h1>Успешный успех!</h1>
        <p>На указанный адрес были отправлены дальнейшие инструкции.</p>
        <p>Если вы не получили письмо, проверьте правильность написания указанного E-mail.</p>
    </div>
{% endblock %}

frontier/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

frontier/users/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/users/basic.css' %}">
    <link rel="stylesheet" href="{% static 'css/users/password_reset.css' %}">
{% endblock %}

{% block content %}
    <div class="wrapper">
        <h1>Восстановление пароля</h1>
        <p>Укажите E-mail существующего аккаунта, на него будет выслано письмо для изменения пароля.</p>
        <form method="post">
            {% csrf_token %}

            <div class="input-box">{{ form.email }}<i class="fa-solid fa-envelope"></i></div>
            <div class="form-error">{{ form.email.errors }}</div>

            <button class="btn1" type="submit">Отправить письмо с инструкциями</button>
        </form>
    </div>
{% endblock %}

frontier/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/users/basic.css' %}" rel="stylesheet">
    <link href="{% static 'css/users/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container min-vh-100 d-flex justify-content-center align-items-center obs-container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            <div class="row wrapper">

                <div class="col-12">
                    <h1>Ваш профиль</h1>
                </div>

                <div class="col-lg-4 col-sm-12 text-center">
                    {% if user.profile.photo %}
                        <img src="{{ user.profile.photo.url }}" alt="bruh" class="avatar white-shadow">
                    {% else %}
                        <img src="{% static 'img/default-user.jpg' %}" alt="bruh" class="avatar white-shadow">
                    {% endif %}
                </div>

                <div class="col-lg-8 col-sm-12 justify-content-center align-items-center">
                    <h6>Выберите изображение, которое станет вашим аватаром!</h6>
                    <div class="chose-image-div">
                       <label class="chose-image">Выбрать{{ sub_form.photo }}</label>
                    </div>
                    <div class="form-error">{{ sub_form.photo.errors }}</div>

                </div>

                <div class="col-lg-6 col-sm-12">
                    <div class="input-box">{{ main_form.username }}<i class="fa-solid fa-user"></i></div>
                    <div class="form-error">{{ main_form.username.errors }}</div>

                    <div class="input-box">{{ main_form.first_name }}<i class="fa-solid fa-user"></i></div>
                    <div class="form-error">{{ main_form.first_name.errors }}</div>
                </div>

                <div class="col-lg-6 col-sm-12">
                    <div class="input-box">{{ main_form.email }}<i class="fa-solid fa-envelope"></i></div>
                    <div class="form-error">{{ main_form.email.errors }}</div>

                    <div class="input-box">{{ main_form.last_name }}<i class="fa-solid fa-user"></i></div>
                    <div class="form-error">{{ main_form.last_name.errors }}</div>
                </div>

                {% if not perms.users.social_auth %}
                    <div class="col-12 change-pass-link">
                        <a href="{% url 'users:password_change' %}">Сменить пароль</a>
                    </div>
                {% endif %}

                <div class="col-12">
                    <button type="submit" class="btn1">Подтвердить</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

frontier/users/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static 'css/users/basic.css' %}">
    <link rel="stylesheet" href="{% static 'css/users/registration.css' %}">
{% endblock %}

{% block content %}
    <div class="container min-vh-100 d-flex justify-content-center align-items-center obs-container">
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            <div class="row wrapper">

                <div class="col-12">
                    <h1>Регистрация</h1>
                </div>

                <div class="col-lg-6 col-sm-12">
                    <div class="input-box">{{ form.username }}<i class="fa-solid fa-user"></i></div>
                    <div class="form-error">{{ form.username.errors }}</div>

                    <div class="input-box">{{ form.first_name }}<i class="fa-solid fa-user"></i></div>
                    <div class="form-error">{{ form.first_name.errors }}</div>

                    <div class="input-box">{{ form.password1 }}<i class="fa-solid fa-lock"></i></div>
                    <div class="form-error">{{ form.password1.errors }}</div>
                </div>

                <div class="col-lg-6 col-sm-12">
                    <div class="input-box">{{ form.email }}<i class="fa-solid fa-envelope"></i></div>
                    <div class="form-error">{{ form.email.errors }}</div>

                    <div class="input-box">{{ form.last_name }}<i class="fa-solid fa-user"></i></div>
                    <div class="form-error">{{ form.last_name.errors }}</div>

                    <div class="input-box">{{ form.password2 }}<i class="fa-solid fa-lock"></i></div>
                    <div class="form-error">{{ form.password2.errors }}</div>
                </div>

                <div class="col-12">
                    <button type="submit" class="btn1">Зарегистрироваться</button>
                    <div class="login-link">Уже есть аккаунт? <a
                            href="{% url 'users:login' %}">Войти</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

frontier/users/templates/users/verified_email.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/users/basic.css' %}">
    <link rel="stylesheet" href="{% static 'css/users/password_reset_complete.css' %}">
{% endblock %}

{% block content %}
    <div class="wrapper">
        <h1>E-mail подтвержден!</h1>
        <form method="get" action="{% url 'index' %}">
            <button class="btn1" type="submit">Вернуться на главную страницу</button>
        </form>
    </div>
{% endblock %}