frontier/Frontier/urls.py
from django.contrib import admin
from django.urls import path, include
from titans.views import IndexView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('titans/', include('titans.urls')),
    path('pilots/', include('pilots.urls')),
    path('weapons/', include('weapons.urls')),
    path('users/', include('users.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path("__debug__/", include("debug_toolbar.urls")),
])

# if settings.DEBUG:
#     urlpatterns.append(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

admin.site.site_header = 'Управление сайтом TitanFun2'
admin.site.index_title = 'Администрирование Базы Данных'

frontier/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import *

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', CreateUserView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUserView.as_view(), name='profile'),
    path('password-change/', NewPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', NewPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset/', NewPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', NewPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>', NewPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', NewPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),

]

frontier/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/basic/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/basic/base.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'img/Titanfan2-logo.png' %}" type="image/x-icon">
    {% block css %}{% endblock %}
    <title>{{ title }}</title>
</head>

<body>

{#---------------------------------------------- NavBar Section ------------------------------------------------------#}
<nav class="navbar fixed-top navbar-dark p-md-3 transparent-nav">
    <div class="container">

        {#        ---------------------------Left Offcanvas Button ------------------------#}
        {% if show_content %}
        <button id="open-offvanvas-button" class="navbar-toggler navbar-inverse" type="button"
                data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">
            <span>Содерж.</span>
        </button>
        {% endif %}

        {#        -----------------------------------TF2 Logo-------------------------#}
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'img/Titanfan2-logo.png' %}" alt="Logo" width="40" height="40"
                 class="d-inline-block align-text-top">
            <span class="ps-1">Titan Fun 2</span>
        </a>

        {#        ----------------------Right Offcanvas Button(Menu toggler)----------------------#}
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar"
                aria-controls="offcanvasDarkNavbar">
            <span>Меню</span>
        </button>
    </div>
</nav>


{#--------------------------------------------- Offcanvas Section ----------------------------------------------------#}

{#------------------------------------------ Left Offcanvas(Content) -------------------------------------------------#}
<div class="offcanvas offcanvas-start offcanvas-obs" data-bs-scroll="true"
     data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasScrollingLabel">Содержание</h5>
        <button id="close-offvanvas-button" type="button" class="btn-close btn-close-white"
                data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <nav id="navbar-obs" class="h-100 flex-column align-items-stretch">
            {% block left_offcanvas %}{% endblock %}
        </nav>
    </div>
</div>

{#-------------------------------------------- Right Offcanvas(Menu) -------------------------------------------------#}
<div class="offcanvas offcanvas-end offcanvas-obs" tabindex="-1" id="offcanvasDarkNavbar" data-bs-scroll="true"
     data-bs-backdrop="false"
     aria-labelledby="offcanvasDarkNavbarLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Главное меню</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'titans' %}">Титаны</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'pilots' %}">Пилоты</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'weapons-main-page' %}">Вооружение</a>
            </li>

            {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'admin:index' %}">Администрирование</a>
                </li>
            {% endif %}

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'users:profile' %}">Профиль</a>
                    <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button class="logout" type="submit">Выйти</button>
                    </form>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'users:login' %}">Войти</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>

{% block content %}{% endblock %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="https://kit.fontawesome.com/c0b4b209ad.js" crossorigin="anonymous"></script>
{% block additional_scripts %}{% endblock %}

</body>
</html>

frontier/templates/footer.html
<footer class="footer-dark">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-3 item">
                <h3>Категории</h3>
                <ul>
                    <li><a href="{% url 'titans' %}">Титаны</a></li>
                    <li><a href="{% url 'pilots' %}">Пилоты</a></li>
                    <li><a href="{% url 'weapons-main-page' %}">Вооружение</a></li>
                </ul>
            </div>
            <div class="col-sm-6 col-md-3 item">
                <h3>Временно не доступно</h3>
                <ul>
                    <li><a href="#">;(</a></li>
                    <li><a href="#">;(</a></li>
                    <li><a href="#">;(</a></li>
                </ul>
            </div>
            <div class="col-md-6 item text">
                <h3>TitanFun 2</h3>
                <p>Titan Fun 2 - Это фанатский сайт, созданный по игре Titalfall 2. Здесь есть каталог Титанов и
                    Пилотов, с их оружием и характеристиками.
                </p>
            </div>
            <div class="col item social">
                <a href="https://github.com/Rev-1b">
                    <i class="fa-brands fa-github"></i></a>

                <a href="https://t.me/po4kunada">
                    <i class="fa-brands fa-telegram"></i></a>

                <a href="https://www.facebook.com/profile.php?id=100079029194665&mibextid=JRoKGi">
                    <i class="fa-brands fa-facebook"></i></a>

                <a href="mailto:g.luenkoaleksei@gmail.com">
                    <i class="fa-brands fa-google"></i></a>
            </div>
        </div>
        <p class="copyright">TitanFun2 © 2023</p>
    </div>
</footer>